config/routes.rb
Rails.application.routes.draw do

  root to: "items#index"


  resources :inventories
  resources :items do
    collection do
      post :bulk_delete, to: "items#bulk_destroy"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory.rb
require 'csv'

class Inventory < ApplicationRecord
    belongs_to :item

    # == VALIDATIONS
    validates :sku, presence: true, uniqueness: { case_sensitive: false }
    validates :quantity, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
    validates :par_level, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
    validates :sold, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true

    # == Delegations
    delegate :title, :price, :unit_cost, :description, to: :item

    # Export inventory as csv
    def self.to_csv
        csv_attributes = ["sku", "barcode", "title", "quantity", "price", "unit_cost", "description"]
        CSV.generate(headers: true) do |csv|
            csv << csv_attributes
            all.find_each do |inventory|
                csv << csv_attributes.map do |attribute|
                    inventory.send(attribute)
                end
            end
        end
    end
end

app/models/item.rb
class Item < ApplicationRecord

    # == Associations
    has_one :inventory, dependent: :destroy

    # == Validations
    validates :title, presence: {message: "must be provided"}
    validates :price, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
    validates :unit_cost, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
    validates :compare_at_price, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true

    accepts_nested_attributes_for :inventory

    # == Delegations
    delegate :quantity, :sku, :barcode, to: :inventory

    # == ENUMS
    enum status: %i[active inactive deleted]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[ show edit update destroy ]

  # GET /inventories or /inventories.json
  def index
    @inventories = Inventory.all

    respond_to do |format|
      format.html
      format.csv { send_data @inventories.to_csv, filename: "inventory-as-at-#{Date.today}.csv" }
    end
  end

  # GET /inventories/1 or /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories or /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventory_url(@inventory), notice: "Inventory was successfully created." }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1 or /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to inventory_url(@inventory), notice: "Inventory was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1 or /inventories/1.json
  def destroy
    # Delete inventory item
    @errors = []
    if @inventory.item.destroy
      redirect_to inventories_url, notice: "Item was successfully deleted."
    else
      @errors = @inventory.item.errors.full_messages
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_params
      params.require(:inventory).permit(:sku, :quantity, :par_level, :sold, :barcode, :track_quantity, :item_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[bulk_destroy]
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @item.build_inventory
  end

  # GET /items/1/edit
  def edit

  end

  # POST /items or /items.json
  def create
    @errors = []
    @item = Item.new(item_params)

   format_fields

    if @item.save
      redirect_to edit_item_path(@item), notice: "Product was successfully created."
    else
      @errors = @item.errors.full_messages
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    @errors = []

    @item.assign_attributes(item_params)

    format_fields

    if @item.save
      redirect_to edit_item_path(@item), notice: "Product was successfully updated."
    else
      @errors = @item.errors.full_messages
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @errors = []
    if @item.destroy
      redirect_to items_url, notice: "Item was successfully deleted."
    else
      @errors = @item.errors.full_messages
    end
  end

  # POST /items/bulk_delete
  def bulk_destroy
    
    if(params[:item_ids])
      respond_to do |format|
        if Item.where(id: params[:item_ids]).destroy_all
          format.json { render :index, status: :ok}
        else
          format.json { render json: @type.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def format_fields
      @item.price = (item_params[:price].to_f * 100).to_i if item_params[:price]
      @item.compare_at_price = (item_params[:compare_at_price].to_f * 100).to_i if item_params[:compare_at_price]
      @item.unit_cost = (item_params[:unit_cost].to_f * 100).to_i if item_params[:unit_cost]

      @item.inventory.track_quantity = item_params[:inventory_attributes][:track_quantity] == "1" ? true : false if item_params[:inventory_attributes]
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, 
        :price, 
        :sku, 
        :description, 
        :tags, 
        :status,
        :compare_at_price,
        :unit_cost,
        inventory_attributes: [
          :id,
          :quantity,
          :sku,
          :barcode,
          :track_quantity
        ]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/inventories/_form.html.erb
<%= form_with(model: inventory) do |form| %>
  <% if inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :par_level %>
    <%= form.text_field :par_level %>
  </div>

  <div class="field">
    <%= form.label :sold %>
    <%= form.text_field :sold %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inventories/destroy.js.erb
<% if @errors.any? %>
  document.getElementById("item-notices").innerHTML = '<%=j render partial: "layouts/partials/error_notices", locals: { notices: @errors } %>'
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>
<% if @inventories.any? %>
  <div class="row">
    <div class="col">
      <h2>Inventory</h2>
    </div>
    <div class="col-auto">
      <%= link_to 'Export', inventories_path(format: :csv), class: "btn btn-secondary" %>
    </div>
    <div class="col-auto">
      <%= link_to 'View products', items_path, class: "btn btn-primary" %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card card-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">SKU</th>
              <th scope="col">Product</th>
              <th scope="col">Quantity</th>
              <th scope="col">Price</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @inventories.each_with_index do |inventory, i| %>
              <% if inventory.track_quantity %>
                <tr>
                  <td><%= inventory.sku %></td>
                  <td><%= inventory.title %></td>
                  <td><%= inventory.quantity %></td>
                  <td><%= inventory.price ? inventory.price / 100.0 : "" %></td>
                  <td>
                    <%= link_to 'Edit', edit_item_path(inventory.item), class: "btn btn-info btn-sm" %>
                    <%= link_to 'Delete', inventory, class: "btn btn-danger btn-sm", method: :delete, remote: true, data: {confirm: "Are you sure you want to permanently delete this product?\nThis action is irreversible."} %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col">
      <h2>Inventory</h2>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <p>Your inventory is empty. Go ahead and add some products or enable tracking for your existing products.</p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= link_to 'Add Product', new_item_path, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/partials/_form_fields.html.erb
<div class="card card-body mb-3">
  <h5 class="card-title">Inventory</h5>
  <div class="row">
    <div class="col pb-3">
      <%= f.label :sku, "SKU (Stock Keeping Unit)", class: "form-label" %>
      <%= f.text_field :sku, class: "form-control" %>
    </div>
    <div class="col pb-3">
      <%= f.label :barcode, "Barcode (ISBN, UPC, etc)", class: "form-label" %>
      <%= f.text_field :barcode, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="form-check">
        <%= f.check_box :track_quantity, class: "form-check-input" %>
        <%= f.label :track_quantity, "Track quantity", class: "form-check-label" %>
      </div>
    </div>
  </div>
  <hr>
  <h5 class="card-title">Quantity</h5>
  <div class="row">
    <div class="col">
      <%= f.label :quantity, "Available", class: "form-label" %>
      <%= f.number_field :quantity, min: 0, class: "form-control" %>
    </div>
  </div>
</div>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @inventory.quantity %>
</p>

<p>
  <strong>Par level:</strong>
  <%= @inventory.par_level %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @inventory.sold %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>

app/views/items/_form.html.erb
<%= form_for @item, remote: true do |f| %>
  <div class="card card-body mb-3">
    <div class="row">
      <div class="col pb-3">
        <%= f.label :title, "Title", class: "form-label" %>
        <%= f.text_field :title, class: "form-control" , placeholder: "e.g. Cargo pants" %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <%= f.label :description, class: "form-label"  %>
        <%= f.text_area :description, class: "form-control", rows: 5 %>
      </div>
    </div>
  </div>
  <div class="card card-body mb-3">
    <h5 class="card-title">Pricing</h5>
    <div class="row">
      <div class="col">
        <%= f.label :price, class: "form-label" %>
        <%= f.number_field :price, value: @item.price ? @item.price / 100.0 : "", min: 0, step: 0.01, class: "form-control" %>
      </div>
      <div class="col">
        <%= f.label :compare_at_price, class: "form-label" %>
        <%= f.number_field :compare_at_price, value: @item.compare_at_price ? @item.compare_at_price / 100.0 : "", min: 0, step: 0.01, class: "form-control" %>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-6">
        <%= f.label :unit_cost, "Cost per item", class: "form-label" %>
        <%= f.number_field :unit_cost, min: 0, value: @item.unit_cost ? @item.unit_cost / 100.0 : "", step: 0.01, class: "form-control" %>
      </div>
    </div>
  </div>
  <%= f.fields_for :inventory do |i| %>
    <%= render partial: "inventories/partials/form_fields", locals: {f: i} %>
  <% end %>
  <!-- 
  <div class="card card-body mb-3">
    <h5 class="card-title">Inventory</h5>
    <div class="row">
      <div class="col pb-3">
        <%= f.label :price, class: "form-label" %>
        <%= f.number_field :price, min: 0, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="form-check">
          <%= check_box_tag :track_quantity, "", true, class: "form-check-input" %>
          <%= label_tag :track_quantity, "Track quantity", class: "form-check-label" %>
        </div>
      </div>
    </div>
    <hr>
    <h5 class="card-title">Quantity</h5>
    <div class="row">
      <div class="col">
        <%= f.label :price, "Available", class: "form-label" %>
        <%= f.number_field :price, min: 0, class: "form-control" %>
      </div>
    </div>
  </div>
  -->
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary float-end" %>
  </div>
<% end %>

app/views/items/create.js.erb
<% if @errors.any? %>
  document.getElementById("item-notices").innerHTML = '<%=j render partial: "layouts/partials/error_notices", locals: { notices: @errors } %>'
<% end %>

app/views/items/destroy.js.erb
<% if @errors.any? %>
  document.getElementById("item-notices").innerHTML = '<%=j render partial: "layouts/partials/error_notices", locals: { notices: @errors } %>'
<% end %>

app/views/items/edit.html.erb
<div class="row">
  <div class="col">
    <%= link_to 'Products', items_path %>
  </div>
</div>
<div class="row">
  <div class="col">
    <h2><%= @item.title %></h2>
  </div>
</div>
<div class="row">
  <div class="col-6">
    <div id="item-notices">
      <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>
    </div>
    <%= render 'form', item: @item %>
  </div>
</div>

app/views/items/index.html.erb
<% if notice %>
  <div id="notice" class="alert alert-success" role="alert">
    <%= notice  %>
  </div>
<% end %>
<% if @items.any? %>
  <div class="row">
    <div class="col">
      <h2>Products</h2>
    </div>
    <div class="col-auto">
      <%= button_tag 'Delete product(s)', id: "bulk-delete-button", class: "btn btn-danger", type: "button" %>
      <%#= link_to 'Delete product(s)', new_item_path, class: "btn btn-danger" %>
    </div>
    <div class="col-auto">
      <%= link_to 'Add product', new_item_path, class: "btn btn-primary" %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card card-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Product</th>
              <th scope="col">Inventory</th>
              <%# <th scope="col">Type</th> %>
              <th scope="col">Actions</th>
              <%# <th scope="col">SKU</th> %>
            </tr>
          </thead>
          <tbody>
            <% @items.each do |item| %>
              <tr>
                <th scope="row">
                  <%= check_box_tag "item_ids[]", item.id, false, class: 'item_ids', data: {item_id: item.id} %>
                </th>
                <td><%= item.title %></td>
                <td><%= item.inventory&.track_quantity ? item.inventory.quantity : "Inventory not tracked" %></td>
                <%# <td></td> %>
                <td>
                  <%= link_to 'Edit', edit_item_path(item), class: "btn btn-info btn-sm" %>
                  <%= link_to 'Delete', item, class: "btn btn-danger btn-sm", method: :delete, remote: true, data: {confirm: "Are you sure you want to permanently delete this product?\nThis action is irreversible."} %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col">
      <h2>Products</h2>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <p>You have no products yet</p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= link_to 'Add Product', new_item_path, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<script>
  var elements = document.getElementsByClassName("item_ids");
  for (let i = 0; i < elements.length; i++) {
    elements[i].addEventListener("click", (event) => {
      if(event.target.checked) {
        event.target.closest("tr").classList.add("table-secondary")
      } else {
        event.target.closest("tr").classList.remove("table-secondary")
      }
    }, false)
  }
  
  document.getElementById("bulk-delete-button")?.addEventListener("click", event => {
    event.preventDefault()
    // Confirm items bulk deletion
    if(confirm("Are you sure you want to permanently delete the selected items?\nThis action is irreversible.")) {
      // Fetch selected items
      let selecedItemIds = []
      let items = document.getElementsByClassName("item_ids");
      for (let i = 0; i < items.length; i++) {
        if(items[i].checked) {
          selecedItemIds.push(items[i].dataset.itemId)
        }
      }
  
      // Bulk delete selected items
      if(selecedItemIds.length > 0) {
        fetch("/items/bulk_delete", {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({ item_ids: selecedItemIds})
        }).then(response => {
          console.log(response)
          if(response.statusText == "OK") {
            alert("Items deleted successfully")
            window.location.replace("<%= items_path %>")
          } else {
            alert("Could not delete items")
          }
        })
      }
    }
  },false)
</script>

app/views/items/index.js.erb
alert("yhhhss")

app/views/items/new.html.erb
<div class="row">
  <div class="col">
    <%= link_to 'Products', items_path %>
  </div>
</div>
<div class="row">
  <div class="col">
    <h2>Add Product</h2>
  </div>
</div>
<div class="row">
  <div class="col-6">
    <div id="item-notices">
    </div>
    <%= render 'form', item: @item %>
    <%#= link_to 'Back', items_path %>
  </div>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @item.title %>
</p>
<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>
<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>
<p>
  <strong>Tags:</strong>
  <%= @item.tags %>
</p>
<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>
<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/items/update.js.erb
<% if @errors.any? %>
  document.getElementById("item-notices").innerHTML = '<%=j render partial: "layouts/partials/error_notices", locals: { notices: @errors } %>'
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InventoryTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body style="display: flex; flex-flow: column; height: 100vh;">
    <header>
      <div class="bg-dark py-1 px-2">
        <h1 class="text-white">Inventory Tracker</h1>
      </div>
    </header>
    <div class="container-fluid py-2" style="flex: 1;">
      <div class="row">
        <div class="col-md-2">
          <%= link_to "All Products", items_path %> <br>
          <%= link_to "Inventories", inventories_path %>
        </div>
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>
    <footer>Copyright 2022</footer>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/partials/_error_notices.html.erb
<% notices.each do |notice| %>
  <div class="alert alert-danger" role="alert">
    <%= notice %>
  </div>
<% end %>

app/views/layouts/partials/_success_notices.html.erb
<% notices.each do |notice| %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>